### ISSUE TITLE
Loading Whisper Model outside method/function

### ISSUE THREAD

**Issue by nGenieDeveloper** [Maphikza/transcriber_with_editor#1]
Loading the whisper model outside of the method transcribe, you will have your Memory(RAM), that will load your model 2 times, see images below, I don't think the streamlit was a bad choice, however ty to share!
<img width="1920" alt="Model_out_of_method" src="https://user-images.githubusercontent.com/68067993/227732087-30ae552e-e884-4c59-b105-eadddfa7c02f.png">
<img width="1920" alt="Model_load_inside_function" src="https://user-images.githubusercontent.com/68067993/227732096-d8ccaba7-1012-40d9-98f8-a0e0cc738e42.png">

:)

**Comment by Maphikza** [comment]
Thank you for this submission. You suggested a great fix and I have fixed it. I will definitely share more. Thank you for taking the time to inform me about the issue.
